### ISSUE TITLE
 how to implement tags in this library

### ISSUE THREAD

**Issue by jhfredy** [mathieu-bour/laravel-cache-fallback#6]
Greetings

I tried to implement this library in a Laravel project, but I realized that it does not support tags, what would be needed for this library to implement the use of tags

Thanks

**Comment by matbour** [comment]
There is sadly no obvious way to handle tags with this library, especially if the fallback cache does not support tags.
If anyone has an idea on how to implement the cache tags, I'll be very happy to work on it.
